# Generated by Django 4.1.2 on 2022-10-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='simple_context',
            field=models.TextField(default=''),
        ),
    ]
