# Generated by Django 4.1.2 on 2022-10-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_remove_topic_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeuser',
            name='avatar',
            field=models.ImageField(upload_to='avatars/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='picture',
            field=models.ImageField(upload_to='pictures/%Y/%m/%d'),
        ),
    ]
