# Generated by Django 4.1.2 on 2022-10-31 18:50

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_alter_activeuser_avatar_alter_topic_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
