# Generated by Django 4.1.2 on 2022-11-25 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0006_onetimecode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='picture',
        ),
    ]
